### ISSUE TITLE
树莓派安装 panic

### ISSUE THREAD

**Issue by ericliang** [maxim-top/maxim-bistro#2]
```
$ sudo ./maxim.ctl install --net internal --token-file ./maxim.token.1585552263725.txt 
[sudo] password for pi: 
request error: Post https://cupid.maximtop.com/cluster/create_script_output: dial tcp 112.126.120.97:443: i/o timeout
panic: Post https://cupid.maximtop.com/cluster/create_script_output: dial tcp 112.126.120.97:443: i/o timeout

goroutine 1 [running]:
panic(0x291ac0, 0x442072a1b0)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x390
main.CreateScriptOutput(0x44200fa000, 0x2ac, 0xffffeae5a872, 0x7, 0x0, 0x0)
	/source/cloud_management/scripts/maximctl.go:669 +0x304
main.InitScriptOutput()
	/source/cloud_management/scripts/maximctl.go:166 +0xf8
main.main()
	/source/cloud_management/scripts/maximctl.go:34 +0xb0
```

**Comment by theorix** [comment]
这个是网络请求超时了，重试下就可以了

**Comment by ericliang** [comment]
不过现在好像还是要先运行 prepare 哦，安装完成啦，记录一下。

`sudo ./maxim.ctl prepare --auto-reboot`
